---
# RKE2/K3S Ansible Role - 默认变量配置
# 作者: DevOps Team
# 版本: 1.0.0

# ============================================================================
# 集群基础配置
# ============================================================================

# 集群类型: rke2 或 k3s
cluster_type: "rke2"

# 节点角色: server 或 agent
node_role: "server"

# 安装版本 (例如: v1.28.5+rke2r1 或 v1.28.5+k3s1，留空则安装最新稳定版)
install_version: ""

# ============================================================================
# 中国大陆特殊配置
# ============================================================================

# 是否为中国大陆地区 (启用时使用 rancher.cn 镜像源)
china_region: false

# 是否配置 containerd 镜像加速 (中国大陆地区建议启用)
enable_registry_mirrors: "{{ china_region }}"

# ============================================================================
# 集群初始化配置
# ============================================================================

# 是否为集群的第一个 server 节点 (仅第一个 server 设置为 true)
cluster_init: false

# Server URL (HA 模式下指向负载均衡器地址，例如: https://lb.example.com:9345)
# Agent 节点和后续 Server 节点必须配置此参数
server_url: ""

# 集群共享 Token (用于节点加入集群，建议使用 ansible-vault 加密)
# 首个 server 节点可留空，系统会自动生成
cluster_token: ""

# ============================================================================
# TLS 配置
# ============================================================================

# TLS SAN 列表 (负载均衡器地址、VIP、域名等)
tls_san:
  []
  # - "lb.example.com"
  # - "192.168.1.100"
  # - "k8s.example.com"

# ============================================================================
# 网络配置
# ============================================================================

# Cluster CIDR (Pod 网络)
cluster_cidr: ""  # 留空使用默认值 (RKE2: 10.42.0.0/16, K3S: 10.42.0.0/16)

# Service CIDR
service_cidr: ""  # 留空使用默认值 (RKE2: 10.43.0.0/16, K3S: 10.43.0.0/16)

# Cluster DNS
cluster_dns: ""  # 留空使用默认值 (10.43.0.10)

# CNI 插件 (RKE2: canal/calico/cilium, K3S: 默认使用 flannel)
cni: ""

# ============================================================================
# 节点配置
# ============================================================================

# 节点标签
node_labels: []
# - "node.kubernetes.io/role=worker"
# - "environment=production"

# 节点污点 (例如: 控制平面节点不运行工作负载)
node_taints: []
# - "node-role.kubernetes.io/control-plane:NoSchedule"

# 节点名称 (留空则使用主机名)
node_name: ""

# ============================================================================
# 存储配置
# ============================================================================

# 数据目录
data_dir: ""  # 留空使用默认值

# ============================================================================
# 安全配置
# ============================================================================

# 启用 Secrets 加密
secrets_encryption: false

# 配置文件权限
config_file_mode: "0600"

# ============================================================================
# 高级配置
# ============================================================================

# 禁用的组件 (K3S 可禁用: traefik, servicelb, metrics-server 等)
disable_components: []

# Kubelet 额外参数
kubelet_args: []

# Kube-apiserver 额外参数
kube_apiserver_args: []

# Kube-controller-manager 额外参数
kube_controller_manager_args: []

# Kube-scheduler 额外参数
kube_scheduler_args: []

# ============================================================================
# 备份配置
# ============================================================================

# 启用自动备份
enable_backup: false

# 备份保留数量
etcd_snapshot_retention: 5

# 备份计划 (cron 格式)
etcd_snapshot_schedule: "0 */12 * * *"

# ============================================================================
# 升级配置
# ============================================================================

# 升级前自动备份
backup_before_upgrade: true

# 节点升级超时时间 (秒)
upgrade_timeout: 600

# ============================================================================
# 防火墙配置
# ============================================================================

# 是否配置防火墙规则
configure_firewall: false

# 防火墙类型: firewalld 或 ufw
firewall_type: "firewalld"

# ============================================================================
# 系统优化
# ============================================================================

# 是否禁用 swap
disable_swap: true

# 是否加载内核模块
load_kernel_modules: true

# 是否配置 sysctl 参数
configure_sysctl: true

# ============================================================================
# 安装选项
# ============================================================================

# 安装脚本超时时间 (秒)
install_timeout: 1800

# 服务启动等待时间 (秒)
service_wait_timeout: 300

# 下载重试次数
download_retries: 3

# 是否跳过预检查
skip_preflight: false
