---
# etcd backup tasks

- name: Check node role
  assert:
    that:
      - node_role == 'server'
    fail_msg: "etcd backup can only be executed on Server nodes, current node role: {{ node_role }}"

- name: Display backup information
  debug:
    msg:
      - "=========================================="
      - "Starting etcd data backup"
      - "Backup directory: {{ backup_dir }}"
      - "=========================================="

- name: Check service status
  systemd:
    name: "{{ service_name }}"
  register: service_status

- name: Verify service is running
  assert:
    that:
      - service_status.status.ActiveState == "active"
    fail_msg: "{{ cluster_type | upper }} service is not running, cannot perform backup"

- name: Create backup directory
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: '0700'

- name: Execute etcd snapshot backup
  shell: |
    {{ backup_command }}
  register: backup_result
  changed_when: true

- name: Get latest backup file
  find:
    paths: "{{ backup_dir }}"
    patterns: "snapshot-*"
    file_type: file
  register: backup_files

- name: Display backup file
  debug:
    msg:
      - "Latest backup file:"
      - "{{ backup_files.files | sort(attribute='mtime', reverse=true) | first | json_query('path') }}"
  when: backup_files.matched > 0

- name: Cleanup old backups
  shell: |
    cd {{ backup_dir }}
    ls -t snapshot-* 2>/dev/null | tail -n +{{ etcd_snapshot_retention + 1 }} | xargs -r rm -f
  when: etcd_snapshot_retention is defined
  changed_when: true
  ignore_errors: yes

- name: Backup statistics
  find:
    paths: "{{ backup_dir }}"
    patterns: "snapshot-*"
    file_type: file
  register: backup_count

- name: Display backup statistics
  debug:
    msg:
      - "=========================================="
      - "✓ Backup completed"
      - "Current retained backups: {{ backup_count.matched }}"
      - "Backup directory: {{ backup_dir }}"
      - "=========================================="
