---
# China region specific configuration tasks

- name: Display China region configuration information
  debug:
    msg:
      - "=========================================="
      - "Enabling China region mirror configuration"
      - "Installation script: {{ china_install_script_url }}"
      - "Registry mirrors: {{ enable_registry_mirrors }}"
      - "=========================================="

- name: Create configuration directory
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: '0755'

- name: Configure Containerd registry mirrors
  template:
    src: registries.yaml.j2
    dest: "{{ registries_config }}"
    mode: '0644'
  when: enable_registry_mirrors | bool
  notify: restart {{ cluster_type }}

- name: Set China mirror environment variables
  set_fact:
    install_env_vars: "{{ china_mirror_env }}"

- name: Display mirror configuration
  debug:
    msg:
      - "Containerd registry configuration file: {{ registries_config }}"
      - "Configured registries:"
      - "  - Docker Hub: {{ registry_mirrors['docker.io'] | join(', ') }}"
      - "  - Kubernetes: {{ registry_mirrors['registry.k8s.io'] | join(', ') }}"
      - "  - GitHub CR: {{ registry_mirrors['ghcr.io'] | join(', ') }}"
  when: enable_registry_mirrors | bool
