---
# DNS configuration fix tasks
# Resolves DNS modification issues after RKE2/K3S installation

- name: Check systemd-resolved status
  systemd:
    name: systemd-resolved
  register: resolved_status
  ignore_errors: yes

- name: Display systemd-resolved status
  debug:
    msg: "systemd-resolved status: {{ resolved_status.status.ActiveState | default('not found') }}"

- name: Backup original /etc/resolv.conf
  copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf.backup-{{ ansible_date_time.epoch }}
    remote_src: yes
    mode: '0644'
  when: preserve_dns_config | default(false)
  ignore_errors: yes

- name: Check if /etc/resolv.conf is a symlink
  stat:
    path: /etc/resolv.conf
  register: resolv_conf_stat

- name: Display resolv.conf information
  debug:
    msg: 
      - "resolv.conf is symlink: {{ resolv_conf_stat.stat.islnk | default(false) }}"
      - "Target path: {{ resolv_conf_stat.stat.lnk_source | default('N/A') }}"

# Solution 1: Disable systemd-resolved (if user chooses)
- name: Disable systemd-resolved (if configured)
  block:
    - name: Stop and disable systemd-resolved
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      
    - name: Remove resolv.conf symlink
      file:
        path: /etc/resolv.conf
        state: absent
      when: resolv_conf_stat.stat.islnk | default(false)
    
    - name: Create static resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        mode: '0644'
      when: static_dns_servers | default([]) | length > 0

    - name: Set resolv.conf as immutable (optional)
      file:
        path: /etc/resolv.conf
        attr: i
      when: 
        - immutable_resolv_conf | default(false)
        - static_dns_servers | default([]) | length > 0
      ignore_errors: yes

  when: 
    - disable_systemd_resolved | default(false)
    - resolved_status.status is defined
    - resolved_status.status.LoadState == "loaded"

# Solution 2: Configure systemd-resolved to not manage DNS
- name: Configure systemd-resolved (keep running but don't manage DNS)
  block:
    - name: Create systemd-resolved configuration directory
      file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        mode: '0755'

    - name: Configure systemd-resolved to not modify resolv.conf
      copy:
        content: |
          [Resolve]
          # Do not modify /etc/resolv.conf
          DNSStubListener=no
        dest: /etc/systemd/resolved.conf.d/disable-stub.conf
        mode: '0644'
      register: resolved_config

    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
      when: resolved_config.changed

    - name: Remove resolv.conf symlink
      file:
        path: /etc/resolv.conf
        state: absent
      when: resolv_conf_stat.stat.islnk | default(false)

    - name: Create static resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        mode: '0644'
      when: static_dns_servers | default([]) | length > 0

  when: 
    - not disable_systemd_resolved | default(false)
    - configure_systemd_resolved | default(false)
    - resolved_status.status is defined
    - resolved_status.status.LoadState == "loaded"

- name: Display DNS configuration recommendations
  debug:
    msg:
      - "=========================================="
      - "⚠️  DNS Configuration Notes"
      - "=========================================="
      - ""
      - "RKE2/K3S does not directly modify host's /etc/resolv.conf"
      - "However, the following situations may cause DNS to be modified:"
      - ""
      - "1. systemd-resolved service"
      - "   - If enabled, will automatically manage /etc/resolv.conf"
      - "   - Recommendation: Disable or configure not to interfere with DNS"
      - ""
      - "2. NetworkManager"
      - "   - May overwrite DNS configuration"
      - "   - Recommendation: Configure NetworkManager not to manage DNS"
      - ""
      - "3. DHCP client"
      - "   - May obtain DNS from DHCP server"
      - "   - Recommendation: Use static DNS configuration"
      - ""
      - "Current configuration options:"
      - "  - disable_systemd_resolved: {{ disable_systemd_resolved | default(false) }}"
      - "  - configure_systemd_resolved: {{ configure_systemd_resolved | default(false) }}"
      - "  - preserve_dns_config: {{ preserve_dns_config | default(false) }}"
      - "  - static_dns_servers: {{ static_dns_servers | default([]) }}"
      - ""
      - "Recommendation: Configure in group_vars/all.yml:"
      - "  disable_systemd_resolved: true  # Disable systemd-resolved"
      - "  static_dns_servers:"
      - "    - 8.8.8.8"
      - "    - 114.114.114.114"
      - "=========================================="
  run_once: yes
