---
# Server node installation tasks

- name: Get initial server node information
  set_fact:
    init_server_host: "{{ groups['rke_servers'] | map('extract', hostvars) | selectattr('cluster_init', 'defined') | selectattr('cluster_init') | map(attribute='inventory_hostname') | first }}"
  when: not cluster_init | bool

- name: Get initial server node IP
  set_fact:
    init_server_ip: "{{ hostvars[init_server_host]['ansible_host'] }}"
  when: not cluster_init | bool

- name: Auto-generate server_url (non-init nodes)
  set_fact:
    server_url: "https://{{ init_server_ip }}:{{ '9345' if cluster_type == 'rke2' else '6443' }}"
  when:
    - not cluster_init | bool
    - server_url is not defined or server_url | length == 0 or 'FIRST_NODE_IP' in server_url

- name: Display server installation information
  debug:
    msg:
      - "=========================================="
      - "Installing {{ cluster_type | upper }} Server node"
      - "Cluster Init: {{ cluster_init }}"
      - "Init Node: {{ init_server_host | default('N/A') }}"
      - "Init Node IP: {{ init_server_ip | default('N/A') }}"
      - "Server URL: {{ server_url | default('N/A', true) }}"
      - "=========================================="

- name: Verify server_url (non-init nodes)
  assert:
    that:
      - server_url is defined
      - server_url | length > 0
      - "'FIRST_NODE_IP' not in server_url"
    fail_msg: "Failed to auto-retrieve server_url, please check init node configuration or manually configure server_url"
  when: not cluster_init | bool

- name: Fetch token from initial server node (non-init nodes)
  slurp:
    src: "{{ token_file }}"
  delegate_to: "{{ groups['rke_servers'] | map('extract', hostvars) | selectattr('cluster_init', 'defined') | selectattr('cluster_init') | map(attribute='inventory_hostname') | first }}"
  register: server_token_content
  when:
    - not cluster_init | bool
    - cluster_token is not defined or cluster_token | length == 0
  ignore_errors: yes

- name: Set token fetched from server (non-init nodes)
  set_fact:
    cluster_token: "{{ server_token_content.content | b64decode | trim }}"
  when:
    - not cluster_init | bool
    - cluster_token is not defined or cluster_token | length == 0
    - server_token_content is defined
    - not server_token_content.failed

- name: Check if local token file exists (fallback)
  stat:
    path: "/tmp/{{ cluster_type }}-token.txt"
  delegate_to: localhost
  become: false
  register: local_token_file
  when:
    - not cluster_init | bool
    - cluster_token is not defined or cluster_token | length == 0

- name: Read token from local file (fallback)
  set_fact:
    cluster_token: "{{ lookup('file', '/tmp/' + cluster_type + '-token.txt') | trim }}"
  when:
    - not cluster_init | bool
    - cluster_token is not defined or cluster_token | length == 0
    - local_token_file.stat.exists

- name: Verify token retrieved (non-init nodes)
  assert:
    that:
      - cluster_token is defined
      - cluster_token | length > 0
    fail_msg: "Failed to retrieve cluster_token, please ensure initial server node is installed or manually configure cluster_token"
  when: not cluster_init | bool

- name: Display token retrieval status (non-init nodes)
  debug:
    msg: "✓ Successfully retrieved cluster_token ({{ 'from init server node' if (server_token_content is defined and not server_token_content.failed) else 'from local file' }})"
  when: not cluster_init | bool

- name: Update local token file (non-init nodes)
  copy:
    content: "{{ cluster_token }}"
    dest: "/tmp/{{ cluster_type }}-token.txt"
    mode: '0600'
  delegate_to: localhost
  become: false
  when:
    - not cluster_init | bool
    - cluster_token is defined
    - cluster_token | length > 0

- name: Create configuration directory
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: '0755'

- name: Generate configuration file
  template:
    src: config.yaml.j2
    dest: "{{ config_file }}"
    mode: "{{ config_file_mode }}"
  notify: restart {{ cluster_type }}

- name: Download installation script
  get_url:
    url: "{{ china_install_script_url if china_region else install_script_url }}"
    dest: "/tmp/{{ cluster_type }}-install.sh"
    mode: '0755'
    timeout: 120
  retries: "{{ download_retries }}"
  delay: 5

- name: Set installation environment variables
  set_fact:
    install_env: "{{ install_env_vars | default({}) }}"

- name: Add version environment variable (RKE2)
  set_fact:
    install_env: "{{ install_env | combine({'INSTALL_RKE2_VERSION': install_version}) }}"
  when:
    - cluster_type == 'rke2'
    - install_version is defined
    - install_version | length > 0

- name: Add version environment variable (K3S)
  set_fact:
    install_env: "{{ install_env | combine({'INSTALL_K3S_VERSION': install_version}) }}"
  when:
    - cluster_type == 'k3s'
    - install_version is defined
    - install_version | length > 0

- name: Execute installation script (RKE2)
  shell: |
    {% for key, value in install_env.items() %}
    export {{ key }}="{{ value }}"
    {% endfor %}
    INSTALL_RKE2_TYPE="server" sh /tmp/{{ cluster_type }}-install.sh
  args:
    creates: "{{ binary_path }}"
  async: "{{ install_timeout }}"
  poll: 15
  when: cluster_type == 'rke2'

- name: Execute installation script (K3S Server)
  shell: |
    {% for key, value in install_env.items() %}
    export {{ key }}="{{ value }}"
    {% endfor %}
    INSTALL_K3S_EXEC="server" sh /tmp/{{ cluster_type }}-install.sh
  args:
    creates: "{{ binary_path }}"
  async: "{{ install_timeout }}"
  poll: 15
  when: cluster_type == 'k3s'

- name: Start service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for service ready
  wait_for:
    path: "{{ kubeconfig_path }}"
    timeout: "{{ service_wait_timeout }}"
  when: cluster_init | bool

- name: Wait for API server ready
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: "{{ api_port }}"
    timeout: "{{ service_wait_timeout }}"

- name: Retrieve node token (init node)
  slurp:
    src: "{{ token_file }}"
  register: node_token_content
  when: cluster_init | bool

- name: Display node token (init node)
  debug:
    msg:
      - "=========================================="
      - "Cluster Token (save it for other nodes to join):"
      - "{{ node_token_content.content | b64decode | trim }}"
      - "=========================================="
  when:
    - cluster_init | bool
    - node_token_content is defined

- name: Save token to local file
  copy:
    content: "{{ node_token_content.content | b64decode | trim }}"
    dest: "/tmp/{{ cluster_type }}-token.txt"
    mode: '0600'
  delegate_to: localhost
  become: false
  when:
    - cluster_init | bool
    - node_token_content is defined

- name: Configure kubectl environment variables
  blockinfile:
    path: "/root/.bashrc"
    block: |
      # {{ cluster_type | upper }} kubectl configuration
      export KUBECONFIG={{ kubeconfig_path }}
      export PATH=$PATH:/var/lib/rancher/{{ cluster_type }}/bin
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ cluster_type | upper }}"
    create: yes

- name: Create kubectl symlink (RKE2)
  file:
    src: "/var/lib/rancher/rke2/bin/kubectl"
    dest: "/usr/local/bin/kubectl"
    state: link
  when: cluster_type == 'rke2'

- name: Verify node status
  shell: |
    export KUBECONFIG={{ kubeconfig_path }}
    {{ kubectl_path }} get nodes
  register: node_status
  retries: 30
  delay: 20
  until: node_status.rc == 0
  changed_when: false

- name: Display node status
  debug:
    var: node_status.stdout_lines

- name: Server installation completed
  debug:
    msg:
      - "=========================================="
      - "✓ {{ cluster_type | upper }} Server node installed successfully"
      - "Kubeconfig: {{ kubeconfig_path }}"
      - "API Server: https://{{ ansible_default_ipv4.address }}:{{ api_port }}"
      - "=========================================="
