---
# RKE2/K3S Ansible Role - Main task entry point

- name: Load cluster-specific variables
  include_vars: "{{ cluster_type }}.yml"
  tags: always

- name: Load China mirror configuration
  include_vars: china_mirrors.yml
  when: china_region | bool
  tags: always

- name: Display cluster configuration
  debug:
    msg:
      - "=========================================="
      - "Cluster Type: {{ cluster_type | upper }}"
      - "Node Role: {{ node_role | upper }}"
      - "China Region: {{ china_region }}"
      - "Cluster Init: {{ cluster_init }}"
      - "Install Version: {{ install_version | default('Latest stable version', true) }}"
      - "=========================================="
  tags: always

- name: Preflight environment check
  include_tasks: preflight.yml
  when: not skip_preflight | bool
  tags:
    - preflight
    - install

- name: Configure DNS (prevent modifications)
  include_tasks: dns_fix.yml
  when: 
    - disable_systemd_resolved | default(false) or configure_systemd_resolved | default(false)
  tags:
    - dns
    - install

- name: Configure China region settings
  include_tasks: configure_china.yml
  when: china_region | bool
  tags:
    - china
    - install

- name: Install server node
  include_tasks: install_server.yml
  when: node_role == "server"
  tags:
    - install
    - server

- name: Install agent node
  include_tasks: install_agent.yml
  when: node_role == "agent"
  tags:
    - install
    - agent

- name: Backup etcd data
  include_tasks: backup.yml
  when:
    - node_role == "server"
    - enable_backup | bool
  tags:
    - backup
    - never  # Requires explicit --tags backup to execute

- name: Upgrade cluster
  include_tasks: upgrade.yml
  when: upgrade_cluster is defined and upgrade_cluster | bool
  tags:
    - upgrade
    - never  # Requires explicit --tags upgrade to execute
