---
# 中国大陆特殊配置任务

- name: 显示中国区配置信息
  debug:
    msg:
      - "=========================================="
      - "启用中国大陆镜像源配置"
      - "安装脚本: {{ china_install_script_url }}"
      - "镜像加速: {{ enable_registry_mirrors }}"
      - "=========================================="

- name: 创建配置目录
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: '0755'

- name: 配置 Containerd 镜像加速
  template:
    src: registries.yaml.j2
    dest: "{{ registries_config }}"
    mode: '0644'
  when: enable_registry_mirrors | bool
  notify: restart {{ cluster_type }}

- name: 设置中国镜像环境变量
  set_fact:
    install_env_vars: "{{ china_mirror_env }}"

- name: 显示镜像配置
  debug:
    msg:
      - "Containerd 镜像源配置文件: {{ registries_config }}"
      - "已配置的镜像仓库:"
      - "  - Docker Hub: {{ registry_mirrors['docker.io'] | join(', ') }}"
      - "  - Kubernetes: {{ registry_mirrors['registry.k8s.io'] | join(', ') }}"
      - "  - GitHub CR: {{ registry_mirrors['ghcr.io'] | join(', ') }}"
  when: enable_registry_mirrors | bool
