---
# RKE2/K3S Backup Playbook
# Purpose: Backup etcd data from all Server nodes

- name: Backup etcd snapshots
  hosts: rke_servers
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Display backup information
      debug:
        msg:
          - "=========================================="
          - "Starting Server node backup: {{ inventory_hostname }}"
          - "=========================================="

  tasks:
    - name: Load cluster-specific variables
      include_vars: "../roles/rancher_cluster/vars/{{ cluster_type }}.yml"

    - name: Execute backup
      include_role:
        name: rancher_cluster
        tasks_from: backup

  post_tasks:
    - name: Backup completion notification
      debug:
        msg:
          - "=========================================="
          - "✓ All Server nodes backup completed"
          - ""
          - "Backup file location:"
          - "  - /var/lib/rancher/{{ cluster_type }}/server/db/snapshots/"
          - ""
          - "Restore command example:"
          - "  - {{ cluster_type }} server --cluster-reset --cluster-reset-restore-path=<snapshot-file>"
          - "=========================================="
      run_once: yes
