---
# Cleanup residual systemd service files
# Purpose: Remove residual RKE2/K3S service files from /usr/local/lib/systemd/system/

- name: Cleanup residual systemd service files
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Display cleanup information
      debug:
        msg:
          - "=========================================="
          - "Cleaning node: {{ inventory_hostname }}"
          - "=========================================="

    - name: Stop and disable RKE2 services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - rke2-server
        - rke2-agent
      ignore_errors: yes

    - name: Stop and disable K3S services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - k3s
        - k3s-agent
      ignore_errors: yes

    - name: Remove systemd service files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        # /etc/systemd/system/
        - "/etc/systemd/system/rke2-server.service"
        - "/etc/systemd/system/rke2-agent.service"
        - "/etc/systemd/system/k3s.service"
        - "/etc/systemd/system/k3s-agent.service"
        # /usr/lib/systemd/system/
        - "/usr/lib/systemd/system/rke2-server.service"
        - "/usr/lib/systemd/system/rke2-agent.service"
        - "/usr/lib/systemd/system/k3s.service"
        - "/usr/lib/systemd/system/k3s-agent.service"
        # /usr/local/lib/systemd/system/ (RKE2's default location)
        - "/usr/local/lib/systemd/system/rke2-server.service"
        - "/usr/local/lib/systemd/system/rke2-agent.service"
        - "/usr/local/lib/systemd/system/k3s.service"
        - "/usr/local/lib/systemd/system/k3s-agent.service"
      register: cleanup_result

    - name: Count deleted files
      set_fact:
        deleted_count: "{{ cleanup_result.results | selectattr('changed', 'equalto', true) | list | length }}"

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      when: deleted_count | int > 0

    - name: Display cleanup results
      debug:
        msg:
          - "✓ Deleted {{ deleted_count }} service files"
          - "✓ systemd reloaded"
      when: deleted_count | int > 0

    - name: Display no residual information
      debug:
        msg: "✓ No residual service files found"
      when: deleted_count | int == 0

  post_tasks:
    - name: Completion notification
      debug:
        msg:
          - "=========================================="
          - "✓ systemd cleanup completed"
          - ""
          - "You can now re-run verification:"
          - "  make verify-uninstall"
          - ""
          - "Or redeploy cluster:"
          - "  make install"
          - "=========================================="
      run_once: yes
