---
# RKE2/K3S Uninstall Playbook
# Purpose: Completely uninstall RKE2 or K3S cluster
# Warning: This operation will delete all data, use with caution!

- name: Uninstall RKE2/K3S cluster
  hosts: all
  become: yes
  gather_facts: yes

  vars_prompt:
    - name: confirm_uninstall
      prompt: "Confirm cluster uninstallation? All data will be deleted! (yes/no)"
      private: no

  pre_tasks:
    - name: Load cluster type variables
      set_fact:
        cluster_type: "{{ cluster_type | default('rke2') }}"
      run_once: yes
    - name: Verify confirmation
      assert:
        that:
          - confirm_uninstall == 'yes'
        fail_msg: "Uninstall operation cancelled"
      run_once: yes

    - name: Display uninstall warning
      debug:
        msg:
          - "=========================================="
          - "⚠️  Warning: Starting {{ cluster_type | upper }} uninstallation"
          - "Host: {{ inventory_hostname }}"
          - "All data will be permanently deleted!"
          - "=========================================="

  tasks:
    - name: Load cluster type variables
      include_vars: "../roles/rancher_cluster/vars/{{ cluster_type }}.yml"

    - name: Stop service
      systemd:
        name: "{{ service_name }}"
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Execute uninstall script (RKE2)
      shell: |
        /usr/local/bin/rke2-uninstall.sh
      when:
        - cluster_type == 'rke2'
      ignore_errors: yes

    - name: Execute uninstall script (K3S Server)
      shell: |
        /usr/local/bin/k3s-uninstall.sh
      when:
        - cluster_type == 'k3s'
        - node_role == 'server'
      ignore_errors: yes

    - name: Execute uninstall script (K3S Agent)
      shell: |
        /usr/local/bin/k3s-agent-uninstall.sh
      when:
        - cluster_type == 'k3s'
        - node_role == 'agent'
      ignore_errors: yes

    - name: Remove cluster-specific directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/rancher/{{ cluster_type }}"
        - "/var/lib/rancher/{{ cluster_type }}"
        - "/var/lib/kubelet"
        - "/etc/cni"
        - "/opt/cni"
        - "/var/lib/cni"
        - "/run/k8s"
      ignore_errors: yes

    - name: Remove Rancher parent directories (complete cleanup)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/rancher"
        - "/var/lib/rancher"
      ignore_errors: yes

    - name: Clean iptables rules
      shell: |
        iptables-save | grep -v {{ cluster_type | upper }} | iptables-restore
        ip6tables-save | grep -v {{ cluster_type | upper }} | ip6tables-restore
      ignore_errors: yes

    - name: Remove network interfaces
      shell: |
        ip link delete cni0 2>/dev/null || true
        ip link delete flannel.1 2>/dev/null || true
        ip link delete kube-ipvs0 2>/dev/null || true
      ignore_errors: yes

    - name: Clean environment variable configuration
      blockinfile:
        path: "/root/.bashrc"
        state: absent
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ cluster_type | upper }}"
      ignore_errors: yes

    - name: Remove kubectl symlink
      file:
        path: /usr/local/bin/kubectl
        state: absent
      ignore_errors: yes

    - name: Remove uninstall scripts and binaries
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/usr/local/bin/rke2-uninstall.sh"
        - "/usr/local/bin/k3s-uninstall.sh"
        - "/usr/local/bin/k3s-agent-uninstall.sh"
        - "/usr/local/bin/rke2"
        - "/usr/local/bin/k3s"
        - "/usr/bin/rke2"
        - "/usr/bin/k3s"
      ignore_errors: yes

    - name: Remove systemd service files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/systemd/system/rke2-server.service"
        - "/etc/systemd/system/rke2-agent.service"
        - "/etc/systemd/system/k3s.service"
        - "/etc/systemd/system/k3s-agent.service"
        - "/usr/lib/systemd/system/rke2-server.service"
        - "/usr/lib/systemd/system/rke2-agent.service"
        - "/usr/lib/systemd/system/k3s.service"
        - "/usr/lib/systemd/system/k3s-agent.service"
        - "/usr/local/lib/systemd/system/rke2-server.service"
        - "/usr/local/lib/systemd/system/rke2-agent.service"
        - "/usr/local/lib/systemd/system/k3s.service"
        - "/usr/local/lib/systemd/system/k3s-agent.service"
      ignore_errors: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      ignore_errors: yes

  post_tasks:
    - name: Uninstall completion notification
      debug:
        msg:
          - "=========================================="
          - "✓ {{ cluster_type | upper }} uninstallation completed"
          - ""
          - "Cleaned up:"
          - "  ✓ Services and processes"
          - "  ✓ Configuration files and directories"
          - "  ✓ Data directories (including /etc/rancher and /var/lib/rancher)"
          - "  ✓ Network interfaces and rules"
          - "  ✓ Binary files and uninstall scripts"
          - "  ✓ Systemd service files"
          - "  ✓ CNI configuration and plugins"
          - ""
          - "Recommended actions:"
          - "  1. Reboot system to ensure complete cleanup: sudo reboot"
          - "  2. Check for residual processes: ps aux | grep -E '(rke2|k3s)'"
          - "  3. Check for residual mounts: mount | grep -E '(rke2|k3s)'"
          - "=========================================="
